apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: hotlaps-test
  name: dev-edit
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lars-edit
  namespace: hotlaps-test
subjects:
  - kind: User
    name: lars@factus.dk
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dev-edit
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lars-wolfgang-edit
  namespace: hotlaps-test
subjects:
  - kind: User
    name: lars@wolfgang-andersen.dk
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dev-edit
  apiGroup: rbac.authorization.k8s.io
